const data=[{id:1,title:'яйцо',amount:60800,amountLabel:'60.8k',priceTon:5.62,rateText:'0.00009 TON/Egg'},{id:2,title:'яйцо',amount:1946,amountLabel:'1 946',priceTon:0.18,rateText:'0.00009 TON/Egg'},{id:3,title:'яйцо',amount:1946,amountLabel:'1 946',priceTon:0.18,rateText:'0.00009 TON/Egg'},{id:4,title:'яйцо',amount:1946,amountLabel:'1 946',priceTon:0.18,rateText:'0.00009 TON/Egg'},{id:5,title:'яйцо',amount:3675,amountLabel:'3 675',priceTon:0.26,rateText:'0.00009 TON/Egg'},{id:6,title:'яйцо',amount:3025,amountLabel:'3 025',priceTon:0.22,rateText:'0.00009 TON/Egg'}];
let tab='all',field='price',order='asc';
const grid=document.querySelector('[data-market-grid]');
function card(i){return `<section class="fcm-card market-item"><svg class="fcm-card__frame" viewBox="0 0 100 100" preserveAspectRatio="none"><path d="M9.5 0.5 L99.5 0.5 L99.5 94.2 L91.5 99.5 L0.5 99.5 L0.5 6.8 Z" fill="none" stroke="var(--border)" stroke-width="1"/></svg><div class="fcm-card__body"><div class="market-item__line"><span class="market-item__lineLabel">${i.title}</span><span class="market-item__pill market-item__pill--blue"><img src="../assets/icons/toncoin_ton_logo.svg">${i.amountLabel}</span></div><div class="market-item__line"><span class="market-item__lineLabel">Цена</span><span class="market-item__pill market-item__pill--violet"><img src="../assets/icons/toncoin_ton_logo.svg">${i.priceTon}</span></div><div class="market-item__rate">${i.rateText}</div><button class="retro-gold-btn" style="--rgb-h:24px;--rgb-font-size:12px;--rgb-border:#6DBAFB;--rgb-inner-border:#599FFA;--rgb-top:#6DBAFB;--rgb-bottom:#427FF9;--rgb-dot:rgba(95,205,251,.95);--rgb-background:#6DBAFB;--rgb-text-stroke:#427FF9"><span class="retro-gold-btn__border"></span><span class="retro-gold-btn__surface"></span><span class="retro-gold-btn__dots"></span><span class="retro-gold-btn__text">Купить</span></button></div></section>`;}
function render(){const arr=(tab==='all'?data:data.slice(0,3)).slice().sort((a,b)=>{const d=field==='price'?a.priceTon-b.priceTon:a.amount-b.amount;return order==='asc'?d:-d});grid.innerHTML=arr.map(card).join('');}
render();
document.querySelectorAll('[data-tab]').forEach(b=>b.addEventListener('click',()=>{tab=b.dataset.tab;document.querySelectorAll('[data-tab]').forEach(x=>x.classList.remove('is-active'));b.classList.add('is-active');render();}));
document.querySelector('[data-dropdown-toggle]')?.addEventListener('click',()=>{const m=document.querySelector('[data-dropdown-menu]');m.hidden=!m.hidden});document.querySelectorAll('[data-sort]').forEach(b=>b.addEventListener('click',()=>{field=b.dataset.sort;document.querySelector('[data-dropdown-toggle]').childNodes[0].nodeValue=b.textContent;document.querySelectorAll('[data-sort]').forEach(x=>x.classList.remove('is-active'));b.classList.add('is-active');document.querySelector('[data-dropdown-menu]').hidden=true;render();}));
document.querySelector('[data-order-toggle]')?.addEventListener('click',()=>{order=order==='asc'?'desc':'asc';document.querySelector('.market-controls__fromToIcon').classList.toggle('is-desc',order==='desc');render();});
const modal=document.querySelector('[data-modal]');document.querySelector('[data-open-modal]')?.addEventListener('click',()=>modal.hidden=false);document.querySelector('[data-close-modal]')?.addEventListener('click',()=>modal.hidden=true);modal?.addEventListener('click',e=>{if(e.target===modal)modal.hidden=true});
function calc(){const ton=Number((document.querySelector('[data-ton-input]').value||'').replace(',','.'));const fee=ton*0.05;document.querySelector('[data-fee]').textContent=fee>0?fee.toFixed(3):'—';document.querySelector('[data-receive]').textContent=ton>0?(ton-fee).toFixed(3):'—';}
document.querySelector('[data-ton-input]')?.addEventListener('input',calc);
