import { retroButton } from '../ui/components.js';

function uic(title, rows){
return `<section class="uic-card"><svg class="uic-card__frame" viewBox="0 0 100 100" preserveAspectRatio="none" aria-hidden="true"><path d="M4 0 H100 V92 L97 100 H0 V13 Z" fill="none" stroke="var(--border)" stroke-width="1" stroke-linejoin="miter" vector-effect="non-scaling-stroke"/></svg><div class="uic-card__header"><h3 class="uic-card__title">${title}</h3></div><div class="uic-card__body">${rows}</div></section>`
}
export function renderMining(){
 const rows1=`<div class="uic-card__row"><div class="uic-card__cell uic-card__cell--left"><div class="uic-card__label">Баланс Тон</div><div class="uic-card__value">20,14</div></div><div class="uic-card__cell uic-card__cell--right"><div class="uic-card__label">Баланс SHTK</div><div class="uic-card__value">20,14</div></div></div><div class="uic-card__row"><div class="uic-card__cell uic-card__cell--left"><div class="uic-card__label">Энергия</div><progress class="uic-progress" max="100" value="55" style="--uic-progress-w:45%;--uic-progress-h:12px;--uic-progress-border:#5e63c9;--uic-progress-track:transparent;--uic-progress-fill:#e8f55a" aria-label="Progress"></progress></div><div class="uic-card__cell uic-card__cell--right"><div class="uic-card__value"></div></div></div>`;
 const rows2=`<div class="uic-card__row"><div class="uic-card__cell uic-card__cell--left"><div class="uic-card__label">Блок</div><div class="uic-card__value">20,14</div></div><div class="uic-card__cell uic-card__cell--right"><div class="uic-card__label">Сложность</div><div class="uic-card__value">190,5</div></div></div><div class="uic-card__row"><div class="uic-card__cell uic-card__cell--left"><div class="uic-card__label">Награда</div><div class="uic-card__value"></div></div><div class="uic-card__cell uic-card__cell--right"><div class="uic-card__label">В сети</div><div class="uic-card__value">130</div></div></div>`;
 const rows3=`<div class="uic-card__row"><div class="uic-card__cell uic-card__cell--left"><div class="uic-card__label">Статус</div><span class="uic-pill uic-pill--accent">⋮ Майнинг</span></div><div class="uic-card__cell uic-card__cell--right"><div class="uic-card__label">Shares</div><div class="uic-card__value"></div></div></div><div class="uic-card__row"><div class="uic-card__cell uic-card__cell--left"><div class="uic-card__label">Хэши</div><div class="uic-card__value"></div></div><div class="uic-card__cell uic-card__cell--right"><div class="uic-card__label">Заработано</div><div class="uic-card__value">2 000</div></div></div>`;
 const rows4=`<div class="uic-card__row uic-card__row-no-divider"><div class="uic-card__cell uic-card__cell--left"><div class="uic-card__label"><span>Блок <span class="yellow">#77703</span></span></div><div class="uic-card__value"><span class="white">Создал в <span class="yellow">13:07</span></span></div></div><div class="uic-card__cell uic-card__cell--right"><div class="uic-card__label"><span class="yellow">User321</span></div><div class="uic-card__value"></div></div></div><div class="uic-card__row"><div class="uic-card__cell uic-card__cell--left"><div class="uic-card__label">Моя награда</div><span class="uic-pill uic-pill--success">0.84</span></div><div class="uic-card__cell uic-card__cell--right"><div class="uic-card__label"></div><div class="uic-card__value"></div></div></div>`;
 return `<main class="mining-page"><div class="mining-page__cards">${uic('Мой профиль',rows1)}${uic('Информация',rows2)}${uic('Майнинг',rows3)}</div><div class="mining-page__actions">${retroButton({text:'Стоп'})}</div>${uic('Последние блоки',rows4)}</main>`;
}
